/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumView: typeof import('./../components/views/AlbumView.vue')['default']
    AppSettings: typeof import('./../components/settings/AppSettings.vue')['default']
    ArtistView: typeof import('./../components/views/ArtistView.vue')['default']
    AuthSettings: typeof import('./../components/settings/AuthSettings.vue')['default']
    BlurhashImage: typeof import('./../components/image/BlurhashImage.vue')['default']
    EditorSeasons: typeof import('./../components/segment/EditorSeasons.vue')['default']
    FilterView: typeof import('./../components/FilterView.vue')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiDelete: typeof import('~icons/mdi/delete')['default']
    IMdiFilmstrip: typeof import('~icons/mdi/filmstrip')['default']
    IMdiInformation: typeof import('~icons/mdi/information')['default']
    IMdiKeyboardArrowUp: typeof import('~icons/mdi/keyboard-arrow-up')['default']
    IMdiMovie: typeof import('~icons/mdi/movie')['default']
    IMdiPause: typeof import('~icons/mdi/pause')['default']
    IMdiPlay: typeof import('~icons/mdi/play')['default']
    IMdiPlayPause: typeof import('~icons/mdi/play-pause')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiRayEndArrow: typeof import('~icons/mdi/ray-end-arrow')['default']
    IMdiRayStartArrow: typeof import('~icons/mdi/ray-start-arrow')['default']
    IMdiSkipForward: typeof import('~icons/mdi/skip-forward')['default']
    IMdiTrashCan: typeof import('~icons/mdi/trash-can')['default']
    IMdiVolume: typeof import('~icons/mdi/volume')['default']
    IMdiVolumeMute: typeof import('~icons/mdi/volume-mute')['default']
    ItemImage: typeof import('./../components/image/ItemImage.vue')['default']
    KeyboardKeys: typeof import('./../components/utils/KeyboardKeys.vue')['default']
    Player: typeof import('./../components/player/Player.vue')['default']
    PlayerEditor: typeof import('./../components/player/PlayerEditor.vue')['default']
    PlayerScrubber: typeof import('./../components/player/PlayerScrubber.vue')['default']
    PlusNewSegment: typeof import('./../components/btn/PlusNewSegment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentAdd: typeof import('./../components/segment/SegmentAdd.vue')['default']
    SegmentEdit: typeof import('./../components/segment/SegmentEdit.vue')['default']
    SegmentsBar: typeof import('./../components/segment/SegmentsBar.vue')['default']
    SegmentSlider: typeof import('./../components/segment/SegmentSlider.vue')['default']
    SegmentVisual: typeof import('./../components/segment/SegmentVisual.vue')['default']
    SeriesView: typeof import('./../components/views/SeriesView.vue')['default']
    SettingsDialog: typeof import('./../components/settings/SettingsDialog.vue')['default']
  }
}
