/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppOptions: typeof import('./src/components/settings/AppOptions.vue')['default']
    Auth: typeof import('./src/components/settings/Auth.vue')['default']
    BlurhashImg: typeof import('./src/components/BlurhashImg.vue')['default']
    EditorBar: typeof import('./src/components/editor/visual/EditorBar.vue')['default']
    EditorSeasons: typeof import('./src/components/editor/EditorSeasons.vue')['default']
    FilterView: typeof import('./src/components/FilterView.vue')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiDelete: typeof import('~icons/mdi/delete')['default']
    IMdiFilmstrip: typeof import('~icons/mdi/filmstrip')['default']
    IMdiInformation: typeof import('~icons/mdi/information')['default']
    IMdiMovie: typeof import('~icons/mdi/movie')['default']
    IMdiPause: typeof import('~icons/mdi/pause')['default']
    IMdiPlay: typeof import('~icons/mdi/play')['default']
    IMdiPlayPause: typeof import('~icons/mdi/play-pause')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiRayEndArrow: typeof import('~icons/mdi/ray-end-arrow')['default']
    IMdiRayStartArrow: typeof import('~icons/mdi/ray-start-arrow')['default']
    IMdiSkipForward: typeof import('~icons/mdi/skip-forward')['default']
    IMdiTrashCan: typeof import('~icons/mdi/trash-can')['default']
    IMdiVolume: typeof import('~icons/mdi/volume')['default']
    IMdiVolumeMute: typeof import('~icons/mdi/volume-mute')['default']
    ItemImage: typeof import('./src/components/ItemImage.vue')['default']
    KeyboardKeys: typeof import('./src/components/editor/visual/KeyboardKeys.vue')['default']
    OptionsDialog: typeof import('./src/components/settings/OptionsDialog.vue')['default']
    Player: typeof import('./src/components/editor/visual/Player.vue')['default']
    PlayerScrubber: typeof import('./src/components/editor/visual/PlayerScrubber.vue')['default']
    ReusableModal: typeof import('./src/components/dialog/ReusableModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentAdd: typeof import('./src/components/editor/segment/SegmentAdd.vue')['default']
    SegmentEdit: typeof import('./src/components/editor/segment/SegmentEdit.vue')['default']
    SegmentEditor: typeof import('./src/components/editor/SegmentEditor.vue')['default']
    SegmentEditorMovie: typeof import('./src/components/editor/SegmentEditorMovie.vue')['default']
    SegmentEditorSeries: typeof import('./src/components/editor/SegmentEditorSeries.vue')['default']
    SegmentSlider: typeof import('./src/components/editor/segment/SegmentSlider.vue')['default']
    SegmentVisual: typeof import('./src/components/editor/segment/SegmentVisual.vue')['default']
    SliderEditor: typeof import('./src/components/editor/SliderEditor.vue')['default']
    YesNoModal: typeof import('./src/components/dialog/YesNoModal.vue')['default']
  }
}
